<?xml version="1.0"?>
<package format="2">
  <name>phone_gps_bridge</name>
  <version>0.1.0</version>
  <description>Receive NMEA over TCP, UDP, or USB serial and publish ROS GPS topics.</description>

  <maintainer email="user@todo.todo">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2_ros</depend>
  <exec_depend>python3-serial</exec_depend>

  <export>
  </export>
</package>
